version: "3"

volumes:
  exo_flask_db:

networks:
  flask_net:

services:
  app_flask:
    build: app_flask_image/.
    networks:
      - flask_net
    ports:
      - "5000:5000"

  database_mariadb:
    build: mariadb_image/.
    networks:
      - flask_net
    volumes:
      - exo_flask_db:/var/lib/mysql






